// <auto-generated />
using System;
using Gestionare_Biblioteca;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestionare_Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    partial class BibliotecaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Gestionare_Biblioteca.Carte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Carti");
                });

            modelBuilder.Entity("Gestionare_Biblioteca.Imprumut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataImprumut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataReturnare")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembruId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarteId");

                    b.HasIndex("MembruId");

                    b.ToTable("Imprumuturi");
                });

            modelBuilder.Entity("Gestionare_Biblioteca.Membru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Membri");
                });

            modelBuilder.Entity("Gestionare_Biblioteca.Imprumut", b =>
                {
                    b.HasOne("Gestionare_Biblioteca.Carte", "CarteImprumutata")
                        .WithMany()
                        .HasForeignKey("CarteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestionare_Biblioteca.Membru", "ImprumutataDe")
                        .WithMany("Imprumuturi")
                        .HasForeignKey("MembruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarteImprumutata");

                    b.Navigation("ImprumutataDe");
                });

            modelBuilder.Entity("Gestionare_Biblioteca.Membru", b =>
                {
                    b.Navigation("Imprumuturi");
                });
#pragma warning restore 612, 618
        }
    }
}
